### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: all

### dataset
dataset: sft_low,sft_medium,sft_high
mix_strategy: concat
disable_shuffling: true
template: llama3
cutoff_len: 2048
max_new_tokens: 8096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama3-8b/lora/sft/concat2
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### accelerator
flash_attn: fa2
enable_liger_kernel: true
use_unsloth_gc: true

### train
seed: 42
per_device_train_batch_size: 64
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 0.5
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: sft_grpo_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
