python3 scripts/0_openai_responses_infer.py \
  --model_name_or_path /mnt/dataset1/pretrained_fm/gpt-oss-20b \
  --template gpt \
  --dataset_dir "data" \
  --cutoff_len 1024 \
  --temperature 1.0 \
  --top_p 1.0 \
  --skip_special_tokens False \
  --default_system "" \
  --enable_thinking True \
  --batch_size 1024 \
  --generations_per_sample 5 \
  --max_new_tokens 8096 \
  --openai_base_url http://localhost:8000/v1 \
  --dataset gsm8k_train \
  --save_name gsm8k_train_low_raw.jsonl \
  --reasoning_effort low \
  --concurrency 80 \


python3 scripts/0_openai_responses_infer.py \
  --model_name_or_path /mnt/dataset1/pretrained_fm/gpt-oss-20b \
  --template gpt \
  --dataset_dir "data" \
  --cutoff_len 1024 \
  --temperature 1.0 \
  --top_p 1.0 \
  --skip_special_tokens False \
  --default_system "" \
  --enable_thinking True \
  --batch_size 1024 \
  --generations_per_sample 5 \
  --max_new_tokens 8096 \
  --openai_base_url http://localhost:8000/v1 \
  --dataset gsm8k_train \
  --save_name gsm8k_train_medium_raw.jsonl \
  --reasoning_effort medium \
  --concurrency 80 \


python3 scripts/0_openai_responses_infer.py \
  --model_name_or_path /mnt/dataset1/pretrained_fm/gpt-oss-20b \
  --template gpt \
  --dataset_dir "data" \
  --cutoff_len 1024 \
  --temperature 1.0 \
  --top_p 1.0 \
  --skip_special_tokens False \
  --default_system "" \
  --enable_thinking True \
  --batch_size 1024 \
  --generations_per_sample 5 \
  --max_new_tokens 8096 \
  --openai_base_url http://localhost:8000/v1 \
  --dataset gsm8k_train \
  --save_name gsm8k_train_high_raw.jsonl \
  --reasoning_effort high \
  --concurrency 80 \